### ISSUE TITLE
Display individual kanji information

### ISSUE THREAD

**Issue by hkBattousai** [wareya/nazeka#12]
Today I found this extension and I am very happy with it. THANK YOU VERY MUCH for developing this project.

I would like to make a feature request. This is a Rikai replacement but it lacks a very important feature of Rikai. In all desktop version of Rikai mods, if you press the Shift key when the mouse pointer is over a kanji, it opens the kanji information panel (See the attached screen shot). In that panel many information about the kanji (onyomi, kunyomu, stroke count, radicals, meaning, etc) are listed. For example, if you hover your mouse on the word "妖怪", it recognizes the word as a whole and at first it doesn't list the translation of the first kanji "妖". However, if you press the Shift key, the kanji information panel opens and gives information about it.

You should really implement this feature. All Japanese learners need it. This is what makes Rikai so popular. and unfortunately all other Rikai replacements lack this feature. Nazeka can make a difference by implementing it.

Please consider my idea.

Many thanks.

<img width="940" alt="rikai - individual kanji information" src="https://user-images.githubusercontent.com/8620559/50387368-3bc03e00-070b-11e9-88ad-75700d7195c7.png">
.

**Comment by wareya** [comment]
I've been thinking about what to do about this. Being completely unable to look up individual kanji is very unhelpful, especially considering that some of them really do have consistent meanings and readings.

My main problem is that I don't have a good, accurate source of kanji information. Kanjidic is full of bad "definitions" and screwed up readings, and its composition information is pretty bad.

But if I add kanjidic as a stopgap, then replacing it with something better later would be very disruptive.

People might also "misuse" the feature to look at the individual kanji of words that nazeka *does* recognize. I'm not really one for preventing people from "misusing" software, but if you don't know better, you can confuse yourself a lot.

These are all problems with individual kanji lookup that I personally experienced years ago when I first started learning japanese, and I didn't realize how much I was confusing myself with the feature until a few months later.

There are definitely things that can't be misleading, like:

- Decomposition information
- On'yomi
- Stroke count
- Category (kyouiku, joyo, jinmeiyo, kanken-hyougai, non-kanken-hyougai)
- Unicode codepoint
- Other unicode information (equivalent characters, compatibility replacements, etc)

These are all clearly useful, and if I ever add a kanji lookup mode, I will add them, except for on'yomi, for a reason I will explain below.

But there are things that CAN be misleading:

- Dictionary radical
- Kun'yomi
- Frequency
- Any keywords or definitions in terms of individual english words rather than descriptions of use
- Dictionary indexes (including RTK)

Rationale for being misleading:

Dictionary radicals are only useful if you're looking characters or words up in a paper dictionary.

On'yomi would be nice to show, but showing on'yomi and not kun'yomi would be VERY confusing. Kun'yomi shouldn't be shown at all in individual kanji lookups because kun'yomi are ordinary Japanese words that are written with the kanji. This is unlike on'yomi, which are the *pronunciation* of a particular building block for Chinese loanwords and wasei-kango (Chinese-origin compounds made in Japan).

Frequency is always misleading because every frequency analysis is biased by the selection of material it's generated from. (I say this as someone who maintains a frequency list generated from visual novels.)

Keywords and single-word definitions of kanji are *always* wrong and misleading, unless you go out of your way to specify which definitions are associated with which readings, which absolutely no computer-readable kanji dictionary does.

Dictionary indexes trick new learners into thinking that kanji are more important or less important than they actually are.



At the end of the day, Nazeka is just a tool, and it can only be used in certain ways. Nazeka in particular is designed to be as fast and unobtrusive as a popup/mouseover dictionary can be, and that means that it needs to present as little misleading information as possible, because the user will often look at it for only a tiny fraction of a second and not really think about how to interpret what it's telling them. This is completely fine, but it means that I have to be very careful with what information is shown to the user, and how it's presented.

This already caused design problems. I have a lot of complicated code related to only showing the related/allowed readings/spellings of words when you look up particular other spellings/readings (JMDict actually has information for this), and it has a bunch of bugs. If I didn't have this code, then someone looking up 夕べ might see "さくや" in the list of readings, and get very confused.

I plan on adding an individual kanji lookup mode eventually, but I care too much about implementing it in as harmless of a way as possible to just clone rikaisama's behavior 1:1. I need more time for the design to cook in my head before it's ready.

**Comment by wareya** [comment]
Working on this now. Planning on showing "grade" (kyouiku, jouyou, jimeiyou, hyougai), stroke count, jouyou readings (described as such), and decomposition.

**Comment by wareya** [comment]
![2019-04-11_18-22-38](https://user-images.githubusercontent.com/585488/55996908-d9be2100-5c86-11e9-83ac-09a0b8fb5b60.png)
![2019-04-11_18-23-13](https://user-images.githubusercontent.com/585488/55996915-e2165c00-5c86-11e9-816f-c755a46f7249.png)
![2019-04-11_18-23-51](https://user-images.githubusercontent.com/585488/55996946-02deb180-5c87-11e9-8148-fced2d25ad88.png)
![2019-04-11_18-22-44](https://user-images.githubusercontent.com/585488/55996919-e3478900-5c86-11e9-8f31-002b2a485706.png)

**Comment by wareya** [comment]
Gotta change the on'yomi readings to hiragana then it's done.

**Comment by wtn** [comment]
For category, I suggest kanji abbreviations like: 教育、常用、人名、漢検、表外

> Gotta change the on'yomi readings to hiragana

I think they'd be easier to read as katakana.

**Comment by wareya** [comment]
Closing this issue to indicate that I implemented it, but feel free to complain here about the choices I made while implementing this feature if you want to. Unless closing issues locks them, in which case feel free to open a new one.
