### ISSUE TITLE
[Feature Request] Add a "times mined" column to mining

### ISSUE THREAD

**Issue by Cupbox** [wareya/nazeka#17]
Default behaviour currently is to add a duplicate of the same word if mined again. It would be more useful to add another tab which indicates the number of times an entry has been mined and so a word encountered more can be learnt on a much higher priority.

**Comment by wareya** [comment]
This feature request has more complications than it seems like it does at first glance.

For example, there are valid reasons to mine the same jmdict entry multiple times (e.g. 昨夜（さくや） and 夕べ（ゆうべ） are the same entry), and just disambiguating them on spelling/reading isn't good enough (聞く（きく） and 聴く（きく） are best seen as the same word, but 速い（はやい） and 早い（はやい） are not).

There's also the issue that the mining system just copies the definition text that you currently have visible on the popup, so if you switch to only showing definitions from a J-J dictionary, you'll be mining J-J cards, and it would be weird to treat them like duplicates of J-E cards.

I've considered something related, though, where you can mark specific words to not show their definitions because you know them already, to force yourself to try to remember them the hard way. This isn't about mining, but it's another feature that would work based on the raw jmdict id of the entry rather than the information contained within the entries.

On a side note, and this isn't a way of rejecting the request or anything, if you're having issues because of mining the same words multiple times then there's a good chance that you're mining too many words. I don't know your specific situation, of course. But if it's possible you're building a large backlog of mined cards you're not going to see for a few weeks, it's better to selectively mine things that you're ready to learn but want help learning. If you're building up a large backlog, it gives uncommon words time to lose their context and become harder to learn.

**Comment by wareya** [comment]
I added error reporting for live mining, so if you're using live mining and have your note's unique field set to what you want to check duplicates by, that should tell you if you try mining duplicate cards now. This doesn't change any actual behavior, just shows an error message that I was previously throwing away.

**Comment by Cupbox** [comment]
Sorry for the late reply. Thank you. This will help a lot. I've started following your advice and mine more selectively and it's done wonders for my retention.
