### ISSUE TITLE
[Feature Request] Parse reading and spelling from json dictionary instead of jmdict

### ISSUE THREAD

**Issue by epistularum** [wareya/nazeka#24]
Jmdict readings/spelling are often cluttered and unnecessarily long while json dictionaries tend to be more concise and useful.
De-cluttering those fields is especially useful for Live Mining.

Example:
Jmdict:
````
煙草、莨、烟草
たばこ(gikun)、えんそう、けぶりぐさ、けむりぐさ、タバコ
````
Kenkyuusha:
````
煙草
たばこ
````

**Comment by wareya** [comment]
I don't particularly want to add this. The overwhelming majority of the time, you actually *want* that information, even if you don't realize it, at least when using the dictionary itself. And for mining, it's good to get into a habit of editing your cards anyway, since you want to do things like simplifying or stripping down definitions too. And the more you pay attention to your cards the more likely you are to notice when you mined a word that the sentence wasn't actually using.

I could probably filter out katakana variants of hiragana readings with no problem since they're useless to nazeka, but no promises.

**Comment by epistularum** [comment]
Fair argument.
